export const labels: string[] = [
    'Bitcoin',
    'Ethereum',
    'Tether',
    'BNB',
    'USD Coin',
    'Binance USD',
    'XRP',
    'Dogecoin',
    'Cardano',
    'Polygon',
    'Polkadot',
    'Lido Staked Ether',
    'Shiba Inu',
    'Dai',
    'Solana',
    'TRON',
    'OKB',
    'Litecoin',
    'Uniswap',
    'Wrapped Bitcoin',
    'Avalanche',
    'LEO Token',
    'Cosmos Hub',
    'Chainlink',
    'Ethereum Classic',
    'Stellar',
    'Monero',
    'The Open Network',
    'Cronos',
    'Bitcoin Cash',
    'Algorand',
    'NEAR Protocol',
    'Quant',
    'VeChain',
    'Filecoin',
    'Flow',
    'Terra Luna Classic',
    'Frax',
    'Hedera',
    'Chiliz',
    'MultiversX (Elrond)',
    'Internet Computer',
    'Chain',
    'EOS',
    'Tezos',
    'The Sandbox',
    'ApeCoin',
    'Theta Network',
    'TrueUSD',
    'Pax Dollar',
]
